require('dotenv').config();

module.exports = {
  OUTSCRAPER_API_KEY: process.env.OUTSCRAPER_API_KEY,
  ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
  VERCEL_TOKEN: process.env.VERCEL_TOKEN,
  VERCEL_SCOPE: process.env.VERCEL_SCOPE,
  LEMLIST_API_KEY: process.env.LEMLIST_API_KEY,
  LEMLIST_CAMPAIGN_ID: process.env.LEMLIST_CAMPAIGN_ID,
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_SERVICE_KEY: process.env.SUPABASE_SERVICE_KEY,
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
  DASHBOARD_PASSWORD: process.env.DASHBOARD_PASSWORD,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
};
